first_name=input("Please enter your first name: ")
middle_initiale=input("Please enter your middle initial: ")
last_name=input("Please enter your last name: ")
street_address=input("Please enter your street address: ")
city=input("Please enter your city: ")
state_abbreviation=input("Please enter your state: ")
zip_code=input("Please enter your zip code: ")
phone_number=input("Please enter your phone number: ")
email_address=input("Please enter your email address: ")
print(f"Hello {first_name} {middle_initiale} {last_name}")
print(f"You live on {street_address}, {city}, {state_abbreviation}, {zip_code}")
print(f"Your Personals are {phone_number}, {email_address}")
